# Numpy[1]

In [1]:
import numpy as np
np.__version__

'1.16.4'

In [2]:
list=[1,2,3,4,5]#python list
list2array=np.array(list)#list to numpy array conversion
list2array

array([1, 2, 3, 4, 5])

In [3]:
list2array+10

array([11, 12, 13, 14, 15])

In [4]:
list2array*10

array([10, 20, 30, 40, 50])

In [5]:
list2array/10

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [6]:
list2array.shape
# (1-D)dimension of array

(5,)

In [7]:
list2array.dtype
# data type

dtype('int32')

In [8]:
arr=np.array([[1,2,3],[4,5,6]])
arr
shape=arr.shape
data=arr.dtype
print('[INFO]Shape:{}\n'.format(shape))
print('[INFO]Datatype:{}'.format(data))

[INFO]Shape:(2, 3)

[INFO]Datatype:int32


# Numpy[2]

In [9]:
arr=np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
             [
             [7,8,9],
             [17,18,19]
             ],
    [
        [2,4,6],
        [1,3,7]
    ],
    [
        [2,4,6],
        [1,3,7]
     ]

])
arr.shape

(4, 2, 3)

In [10]:
a=np.array([(1,2),(4,6),(41,16)])
print(a)
print(a.shape)

[[ 1  2]
 [ 4  6]
 [41 16]]
(3, 2)


In [11]:
a.reshape(3,2)
a

array([[ 1,  2],
       [ 4,  6],
       [41, 16]])

In [12]:
a.flatten()
# converts n-dimensional arrray to 1_d

array([ 1,  2,  4,  6, 41, 16])

In [13]:
zeros=np.zeros([3,2])
zeros
# creates matrix having all elements zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
ones=np.ones([4,4],dtype='int16')
ones
# creates matrix with each element 1 of int16 type

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [15]:
ones=np.ones([4,4],dtype='float32')
ones

# creates matrix with each element 1 of float32 type

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

# Numpy[3]


# numpy.hstack() and numpy.vsatck() in python

In [28]:
import numpy as np
f=np.array([1,2,3])
g=np.array([4,5,6])
print('[INFO]Horizontal Append:\n{}'.format(np.hstack((f,g))))

[INFO]Horizontal Append:
[1 2 3 4 5 6]


In [31]:
f=np.array([1,2,3])
g=np.array([4,5,6])
h=np.array([4,5,6])
v=np.vstack((f,g,h))
print('[INFO]Vertical Append:\n{}'.format(v))
v.shape

[INFO]Vertical Append:
[[1 2 3]
 [4 5 6]
 [4 5 6]]


(3, 3)

# Generate Random Numbers
* numpy.random.normal(loc,scale,size)
* loc=the mean
* scale=standard deviation
* size=no of terms

In [40]:
# genrate random no from normal distribution
normal_array=np.random.normal(15,0.5,10)
print(normal_array)

[15.0168489  15.2366022  15.12885654 14.33903406 14.66383101 14.82159792
 14.841162   14.77795498 15.6380003  14.79376601]


# Asarray
* asarray() is used to convert an input like list,tuple into an array
* numpy.asarray(data,dtype=none,order=none)[source]


In [63]:
A=np.matrix(np.ones((4,4))+10)
A

matrix([[11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [11., 11., 11., 11.]])

In [65]:
np.array(A)[2]=5
A
# as an array matrix element cant be change
# output is same

matrix([[11., 11., 11., 11.],
        [11., 11., 11., 11.],
        [ 3.,  3.,  3.,  3.],
        [11., 11., 11., 11.]])

In [77]:
np.asarray(A)[2][2]=33
print(A)
# asarray converts the matrix into array and allow modification
# output is different than previous

[[11. 11. 11. 11.]
 [11. 11. 11. 11.]
 [ 5.  5. 33.  5.]
 [11. 11. 11. 11.]]


In [84]:
np.asarray(A)[1][1]=35
print(A)

[[11. 11. 11. 11.]
 [11. 35. 11. 11.]
 [ 5.  5. 33.  5.]
 [11. 11. 11. 11.]]


In [86]:
np.asarray(A)[2]=0
A

matrix([[11., 11., 11., 11.],
        [11., 35., 11., 11.],
        [ 0.,  0.,  0.,  0.],
        [11., 11., 11., 11.]])

# Arange
* numpy.arange(start,stop,step)

In [89]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

# Numpy[4]

# Indexing and slicing

# array[row_start:row_end,col_start:col_end]

In [103]:
e=np.array([(1,2,3,4),(4,5,6,7),(7,8,9,10),(10,11,12,13)])
print(e)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]
 [10 11 12 13]]


In [104]:
print('[INFO]First row:{}'.format(e[0]))
# index start at 

[INFO]First row:[1 2 3 4]


In [105]:
f_cols=e[:,1]#all rows but first column
f_cols
print('[INFO]First column is:{}'.format(f_cols))

[INFO]First column is:[ 2  5  8 11]


In [110]:
# PRINT 5 AND 8
selected=e[1:3,1]
selected

array([5, 8])

In [111]:
# PRINT 5,6,8,9
e[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [112]:
second_column=e[:,1]
second_column

array([ 2,  5,  8, 11])

In [115]:
second_row=e[1,:]
second_row

array([4, 5, 6, 7])

In [114]:
e[1]

array([4, 5, 6, 7])

# Numpy Stastical function
* Min=np.min()
* Max=np.max()
* Mean=np.mean()
* Median=np.median()
* Standard deviation=np.std()

In [120]:
### Min 
x1=(np.min(normal_array))

### Max 
x2=(np.max(normal_array))

### Mean 
x3=(np.mean(normal_array))

### Median
x4=(np.median(normal_array))

### Sd
x5=(np.std(normal_array))
print('[INFO]Min is:{0}\n[INFO]Max is:{1}\n[INFO]Median is:{2}\n[INFO]Standard \
Deviation is:{3}'.format(x1,x2,x3,x4,x5))

[INFO]Min is:14.339034060047936
[INFO]Max is:15.638000302497176
[INFO]Median is:14.925765391221011
[INFO]Standard Deviation is:14.831379957736779


# DOT PRODUCT
* numpy.dot(x, y, out=None)
* x,y: Input arrays. x and y both should be 1-D or 2-D for the function to work

* out: This is the output argument.For 1-D array scalar is returned. Other wise ndarray

In [124]:
x=np.array([1,2,3])
y=np.array([4,5,6])
# 1*4+2*5+3*6=32
dot_proc=np.dot(x,y)
dot_proc
mat_proc=np.matmul(x,y)
mat_proc

32

# Matrix Multiplication
* numpy.matmul(x, y, out=None)

In [129]:
h = [[1,2],[3,4]] 
i = [[5,6],[7,8]] 
v1=np.matmul(h,i)
v2=np.dot(h,i)
print('[INFO]Dot product is:\n{}\n[INFO]Matrix Multiplication is:\n{}\n'.format(v1,v2))

[INFO]Dot product is:
[[19 22]
 [43 50]]
[INFO]Matrix Multiplication is:
[[19 22]
 [43 50]]

